import { Schema } from "effect";

export const TokenScope = Schema.Array(
  Schema.Literal(
    'benefits:read',
    'benefits:write',
    'checkout_links:read',
    'checkout_links:write',
    'checkouts:read',
    'checkouts:write',
    'custom_fields:read',
    'custom_fields:write',
    'customer_meters:read',
    'customer_portal:read',
    'customer_portal:write',
    'customer_seats:read',
    'customer_seats:write',
    'customer_sessions:write',
    'customers:read',
    'customers:write',
    'discounts:read',
    'discounts:write',
    'disputes:read',
    'email',
    'events:read',
    'events:write',
    'files:read',
    'files:write',
    'license_keys:read',
    'license_keys:write',
    'member_sessions:write',
    'members:read',
    'members:write',
    'meters:read',
    'meters:write',
    'metrics:read',
    'metrics:write',
    'notification_recipients:read',
    'notification_recipients:write',
    'notifications:read',
    'notifications:write',
    'openid',
    'orders:read',
    'orders:write',
    'organization_access_tokens:read',
    'organization_access_tokens:write',
    'organizations:read',
    'organizations:write',
    'payments:read',
    'payouts:read',
    'payouts:write',
    'products:read',
    'products:write',
    'profile',
    'refunds:read',
    'refunds:write',
    'subscriptions:read',
    'subscriptions:write',
    'transactions:read',
    'transactions:write',
    'user:read',
    'user:write',
    'wallets:read',
    'wallets:write',
    'webhooks:read',
    'webhooks:write',
  ),
);

export const Token = Schema.Struct({
  token: Schema.Redacted(Schema.String),
  refreshToken: Schema.Redacted(Schema.String),
  expiresIn: Schema.DurationFromMillis,
  expiresAt: Schema.Date,
  scope: TokenScope,
  server: Schema.Literal("production", "sandbox"),
});
export type Token = Schema.Schema.Type<typeof Token>;
export type TokenJSON = Schema.Schema.Encoded<typeof Token>;

export const Tokens = Schema.Struct({
  production: Schema.optional(Token),
  sandbox: Schema.optional(Token),
});
export type Tokens = Schema.Schema.Type<typeof Tokens>;
export type TokensJSON = Schema.Schema.Encoded<typeof Tokens>;
